2025-04-07 08:29:48.595 +05:30 [INF] Application starting up
2025-04-07 08:29:52.224 +05:30 [INF] Main thread ID: 1
2025-04-07 08:29:52.225 +05:30 [INF] ARGS:- C:\BackOffice\ETL_Replacement\PIL\SBCNSUN\Input\Source\Temp_Process\SBCNSUN_12_v1_20250207_TESTSBCN10.csv
2025-04-07 08:29:52.227 +05:30 [INF] Processing files for domain: PIL, invoiceType: SBCNSUN
2025-04-07 08:29:56.684 +05:30 [WRN] Exception In TempInsertStoreProc: 22023: cannot call json_array_elements on a scalar
2025-04-07 08:29:56.760 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 1
2025-04-07 08:29:56.760 +05:30 [ERR] Exception: 22023: cannot call json_array_elements on a scalar
2025-04-07 08:30:02.065 +05:30 [WRN] Exception In TempInsertStoreProc: 22023: cannot call json_array_elements on a scalar
2025-04-07 08:30:02.117 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 2
2025-04-07 08:30:02.117 +05:30 [ERR] Exception: 22023: cannot call json_array_elements on a scalar
2025-04-07 08:30:07.400 +05:30 [WRN] Exception In TempInsertStoreProc: 22023: cannot call json_array_elements on a scalar
2025-04-07 08:30:07.448 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 3
2025-04-07 08:30:07.449 +05:30 [ERR] Exception: 22023: cannot call json_array_elements on a scalar
2025-04-07 08:30:12.722 +05:30 [WRN] Exception In TempInsertStoreProc: 22023: cannot call json_array_elements on a scalar
2025-04-07 08:30:12.768 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 4
2025-04-07 08:30:12.768 +05:30 [ERR] Exception: 22023: cannot call json_array_elements on a scalar
2025-04-07 08:30:17.997 +05:30 [WRN] Exception In TempInsertStoreProc: 22023: cannot call json_array_elements on a scalar
2025-04-07 08:30:18.044 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 5
2025-04-07 08:30:18.045 +05:30 [ERR] Exception: 22023: cannot call json_array_elements on a scalar
2025-04-07 08:30:23.312 +05:30 [WRN] Exception In TempInsertStoreProc: 22023: cannot call json_array_elements on a scalar
2025-04-07 08:30:23.362 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 6
2025-04-07 08:30:23.363 +05:30 [ERR] Exception: 22023: cannot call json_array_elements on a scalar
2025-04-07 08:30:28.582 +05:30 [WRN] Exception In TempInsertStoreProc: 22023: cannot call json_array_elements on a scalar
2025-04-07 08:30:28.628 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 7
2025-04-07 08:30:28.629 +05:30 [ERR] Exception: 22023: cannot call json_array_elements on a scalar
2025-04-07 08:30:33.879 +05:30 [WRN] Exception In TempInsertStoreProc: 22023: cannot call json_array_elements on a scalar
2025-04-07 08:30:33.925 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 8
2025-04-07 08:30:33.926 +05:30 [ERR] Exception: 22023: cannot call json_array_elements on a scalar
2025-04-07 08:30:39.168 +05:30 [WRN] Exception In TempInsertStoreProc: 22023: cannot call json_array_elements on a scalar
2025-04-07 08:30:39.215 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 9
2025-04-07 08:30:39.216 +05:30 [ERR] Exception: 22023: cannot call json_array_elements on a scalar
2025-04-07 08:30:44.493 +05:30 [WRN] Exception In TempInsertStoreProc: 22023: cannot call json_array_elements on a scalar
2025-04-07 08:30:44.540 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 10
2025-04-07 08:30:44.542 +05:30 [ERR] Exception: 22023: cannot call json_array_elements on a scalar
2025-04-07 08:30:49.862 +05:30 [WRN] Exception In TempInsertStoreProc: 22023: cannot call json_array_elements on a scalar
2025-04-07 08:30:49.911 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 11
2025-04-07 08:30:49.912 +05:30 [ERR] Exception: 22023: cannot call json_array_elements on a scalar
2025-04-07 08:30:55.204 +05:30 [WRN] Exception In TempInsertStoreProc: 22023: cannot call json_array_elements on a scalar
2025-04-07 08:30:55.250 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 12
2025-04-07 08:30:55.251 +05:30 [ERR] Exception: 22023: cannot call json_array_elements on a scalar
2025-04-07 08:31:00.575 +05:30 [WRN] Exception In TempInsertStoreProc: 22023: cannot call json_array_elements on a scalar
2025-04-07 08:31:00.621 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 13
2025-04-07 08:31:00.622 +05:30 [ERR] Exception: 22023: cannot call json_array_elements on a scalar
2025-04-07 08:31:05.934 +05:30 [WRN] Exception In TempInsertStoreProc: 22023: cannot call json_array_elements on a scalar
2025-04-07 08:31:05.980 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 14
2025-04-07 08:31:05.981 +05:30 [ERR] Exception: 22023: cannot call json_array_elements on a scalar
2025-04-07 08:32:34.386 +05:30 [INF] Application starting up
2025-04-07 08:32:35.565 +05:30 [INF] Main thread ID: 1
2025-04-07 08:32:35.565 +05:30 [INF] ARGS:- C:\BackOffice\ETL_Replacement\PIL\SBCNSUN\Input\Source\Temp_Process\SBCNSUN_12_v1_20250207_TESTSBCN10.csv
2025-04-07 08:32:35.569 +05:30 [INF] Processing files for domain: PIL, invoiceType: SBCNSUN
2025-04-07 08:35:08.537 +05:30 [INF] Application starting up
2025-04-07 08:35:09.296 +05:30 [INF] Main thread ID: 1
2025-04-07 08:35:09.297 +05:30 [INF] ARGS:- C:\BackOffice\ETL_Replacement\PIL\SBCNSUN\Input\Source\Temp_Process\SBCNSUN_12_v1_20250207_TESTSBCN10.csv
2025-04-07 08:35:09.299 +05:30 [INF] Processing files for domain: PIL, invoiceType: SBCNSUN
2025-04-07 08:35:58.949 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 1
2025-04-07 08:35:58.949 +05:30 [ERR] Exception: 42883: procedure sbcnsun_insert_12data(p_invoice_number => text, p_totalamount => text, p_totallineitems => text, filepath => json) does not exist

POSITION: 6
2025-04-07 08:37:14.658 +05:30 [INF] Application starting up
2025-04-07 08:37:15.640 +05:30 [INF] Main thread ID: 1
2025-04-07 08:37:15.712 +05:30 [INF] ARGS:- C:\BackOffice\ETL_Replacement\PIL\SBCNSUN\Input\Source\Temp_Process\SBCNSUN_12_v1_20250207_TESTSBCN10.csv
2025-04-07 08:37:15.744 +05:30 [INF] Processing files for domain: PIL, invoiceType: SBCNSUN
2025-04-07 08:37:19.616 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 1
2025-04-07 08:37:19.616 +05:30 [ERR] Exception: 42701: column "cbcsellervatid" specified more than once
2025-04-07 08:44:13.063 +05:30 [INF] Application starting up
2025-04-07 08:44:14.195 +05:30 [INF] Main thread ID: 1
2025-04-07 08:44:14.195 +05:30 [INF] ARGS:- C:\BackOffice\ETL_Replacement\PIL\SBCNSUN\Input\Source\Temp_Process\SBCNSUN_12_v1_20250207_TESTSBCN10.csv
2025-04-07 08:44:14.198 +05:30 [INF] Processing files for domain: PIL, invoiceType: SBCNSUN
2025-04-07 08:44:18.552 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 1
2025-04-07 08:44:18.553 +05:30 [ERR] Exception: 42703: column di.cbcbuyervatid does not exist
2025-04-07 08:53:26.944 +05:30 [INF] Application starting up
2025-04-07 08:53:27.840 +05:30 [INF] Main thread ID: 1
2025-04-07 08:53:27.840 +05:30 [INF] ARGS:- C:\BackOffice\ETL_Replacement\PIL\SBINSUN\Input\Source\Temp_Process\SBINSUN_11_v2_20250207_Test1001.csv
2025-04-07 08:53:27.842 +05:30 [INF] Processing files for domain: PIL, invoiceType: SBINSUN
2025-04-07 08:53:32.583 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 1
2025-04-07 08:53:32.583 +05:30 [ERR] Exception: 42703: column di.cbcbuyervatid does not exist
2025-04-07 09:04:58.309 +05:30 [INF] Application starting up
2025-04-07 09:04:58.609 +05:30 [INF] Main thread ID: 1
2025-04-07 09:04:58.609 +05:30 [INF] ARGS:- C:\BackOffice\ETL_Replacement\PIL\SBINSUN\Input\Source\Temp_Process\SBINSUN_11_v2_20250207_Test2005.csv
2025-04-07 09:04:58.611 +05:30 [INF] Processing files for domain: PIL, invoiceType: SBINSUN
2025-04-07 09:05:15.356 +05:30 [INF] Process file path :- C:\BackOffice\ETL_Replacement\PIL\SBINSUN\Input\Source\Temp_Process\SBINSUN_11_v2_20250207_Test2005.csv
2025-04-07 09:05:15.356 +05:30 [INF] Process file name :- SBINSUN_11_v2_20250207_Test2005.csv
2025-04-07 09:05:15.357 +05:30 [INF] Total time taken in process: 15.6531697 seconds
2025-04-07 09:05:15.359 +05:30 [INF] Total time taken in moving: 0.0017386 seconds
2025-04-07 09:19:09.918 +05:30 [INF] Application starting up
2025-04-07 09:19:10.182 +05:30 [INF] Main thread ID: 1
2025-04-07 09:19:10.182 +05:30 [INF] ARGS:- C:\BackOffice\ETL_Replacement\PIL\SBINSUN\Input\Source\Temp_Process\SBINSUN_11_v2_20250207_Test1001.csv
2025-04-07 09:19:10.184 +05:30 [INF] Processing files for domain: PIL, invoiceType: SBINSUN
2025-04-07 09:19:14.603 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcsellername" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:19:14.604 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 1
2025-04-07 09:19:14.604 +05:30 [ERR] Exception: 42703: column "cbcsellername" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:19:20.414 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcsellername" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:19:20.415 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 2
2025-04-07 09:19:20.415 +05:30 [ERR] Exception: 42703: column "cbcsellername" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:19:26.211 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcsellername" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:19:26.211 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 3
2025-04-07 09:19:26.211 +05:30 [ERR] Exception: 42703: column "cbcsellername" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:19:39.477 +05:30 [INF] Application starting up
2025-04-07 09:19:39.746 +05:30 [INF] Main thread ID: 1
2025-04-07 09:19:39.746 +05:30 [INF] ARGS:- C:\BackOffice\ETL_Replacement\PIL\SBINSUN\Input\Source\Temp_Process\SBINSUN_11_v2_20250207_Test1001.csv
2025-04-07 09:19:39.748 +05:30 [INF] Processing files for domain: PIL, invoiceType: SBINSUN
2025-04-07 09:19:43.401 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcsellername" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:19:43.402 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 1
2025-04-07 09:19:43.402 +05:30 [ERR] Exception: 42703: column "cbcsellername" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:28:15.248 +05:30 [INF] Application starting up
2025-04-07 09:28:15.511 +05:30 [INF] Main thread ID: 1
2025-04-07 09:28:15.512 +05:30 [INF] ARGS:- C:\BackOffice\ETL_Replacement\PIL\SBINSUN\Input\Source\Temp_Process\SBINSUN_11_v2_20250207_Test1001.csv
2025-04-07 09:28:15.513 +05:30 [INF] Processing files for domain: PIL, invoiceType: SBINSUN
2025-04-07 09:28:19.540 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcsellername" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:28:19.540 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 1
2025-04-07 09:28:19.541 +05:30 [ERR] Exception: 42703: column "cbcsellername" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:28:46.033 +05:30 [INF] Application starting up
2025-04-07 09:28:47.019 +05:30 [INF] Main thread ID: 1
2025-04-07 09:28:47.027 +05:30 [INF] ARGS:- C:\BackOffice\ETL_Replacement\PIL\SBINSUN\Input\Source\Temp_Process\SBINSUN_11_v2_20250207_Test1001.csv
2025-04-07 09:28:47.033 +05:30 [INF] Processing files for domain: PIL, invoiceType: SBINSUN
2025-04-07 09:28:51.374 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcsellername" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:28:51.451 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 1
2025-04-07 09:28:51.451 +05:30 [ERR] Exception: 42703: column "cbcsellername" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:31:21.032 +05:30 [INF] Application starting up
2025-04-07 09:31:21.302 +05:30 [INF] Main thread ID: 1
2025-04-07 09:31:21.302 +05:30 [INF] ARGS:- C:\BackOffice\ETL_Replacement\PIL\SBINSUN\Input\Source\Temp_Process\SBINSUN_11_v2_20250207_Test1001.csv
2025-04-07 09:31:21.304 +05:30 [INF] Processing files for domain: PIL, invoiceType: SBINSUN
2025-04-07 09:31:25.325 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:31:25.326 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 1
2025-04-07 09:31:25.326 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:31:31.209 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:31:31.210 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 2
2025-04-07 09:31:31.210 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:34:02.933 +05:30 [INF] Application starting up
2025-04-07 09:34:03.206 +05:30 [INF] Main thread ID: 1
2025-04-07 09:34:03.206 +05:30 [INF] ARGS:- C:\BackOffice\ETL_Replacement\PIL\SBINSUN\Input\Source\Temp_Process\SBINSUN_11_v2_20250207_Test1001.csv
2025-04-07 09:34:03.208 +05:30 [INF] Processing files for domain: PIL, invoiceType: SBINSUN
2025-04-07 09:34:07.658 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:34:07.658 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 1
2025-04-07 09:34:07.659 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:35:00.227 +05:30 [INF] Application starting up
2025-04-07 09:35:00.493 +05:30 [INF] Main thread ID: 1
2025-04-07 09:35:00.493 +05:30 [INF] ARGS:- C:\BackOffice\ETL_Replacement\PIL\SBINSUN\Input\Source\Temp_Process\SBINSUN_11_v2_20250207_Test1001.csv
2025-04-07 09:35:00.495 +05:30 [INF] Processing files for domain: PIL, invoiceType: SBINSUN
2025-04-07 09:35:11.625 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:35:11.625 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 1
2025-04-07 09:35:11.626 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:35:48.937 +05:30 [INF] Application starting up
2025-04-07 09:35:49.208 +05:30 [INF] Main thread ID: 1
2025-04-07 09:35:49.208 +05:30 [INF] ARGS:- C:\BackOffice\ETL_Replacement\PIL\SBINSUN\Input\Source\Temp_Process\SBINSUN_11_v2_20250207_Test1001.csv
2025-04-07 09:35:49.210 +05:30 [INF] Processing files for domain: PIL, invoiceType: SBINSUN
2025-04-07 09:35:55.809 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:35:55.810 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 1
2025-04-07 09:35:55.810 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:36:02.010 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:36:02.010 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 2
2025-04-07 09:36:02.010 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:36:07.792 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:36:07.792 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 3
2025-04-07 09:36:07.792 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:36:13.649 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:36:13.682 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 4
2025-04-07 09:36:13.692 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:36:19.528 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:36:19.528 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 5
2025-04-07 09:36:19.529 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:36:25.049 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:36:25.050 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 6
2025-04-07 09:36:25.050 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:36:30.700 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:36:30.701 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 7
2025-04-07 09:36:30.701 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:36:36.389 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:36:36.389 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 8
2025-04-07 09:36:36.390 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:36:42.138 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:36:42.139 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 9
2025-04-07 09:36:42.139 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:36:48.880 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:36:48.881 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 10
2025-04-07 09:36:48.881 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:36:54.483 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:36:54.483 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 11
2025-04-07 09:36:54.484 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:37:00.166 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:37:00.166 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 12
2025-04-07 09:37:00.167 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:37:06.185 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:37:06.186 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 13
2025-04-07 09:37:06.186 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:37:12.118 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:37:12.119 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 14
2025-04-07 09:37:12.119 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:37:18.008 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:37:18.009 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 15
2025-04-07 09:37:18.010 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:37:23.810 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:37:23.810 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 16
2025-04-07 09:37:23.811 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:37:29.561 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:37:29.562 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 17
2025-04-07 09:37:29.562 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:37:35.446 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:37:35.446 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 18
2025-04-07 09:37:35.447 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:37:41.567 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:37:41.568 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 19
2025-04-07 09:37:41.569 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:37:47.518 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:37:47.519 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 20
2025-04-07 09:37:47.519 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:37:53.267 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:37:53.268 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 21
2025-04-07 09:37:53.268 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:37:59.109 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:37:59.110 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 22
2025-04-07 09:37:59.110 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:38:05.130 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:38:05.131 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 23
2025-04-07 09:38:05.131 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:38:10.772 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:38:10.773 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 24
2025-04-07 09:38:10.773 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:38:16.614 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:38:16.615 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 25
2025-04-07 09:38:16.615 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:38:22.158 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:38:22.158 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 26
2025-04-07 09:38:22.159 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:38:27.842 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:38:27.843 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 27
2025-04-07 09:38:27.843 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:38:33.661 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:38:33.661 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 28
2025-04-07 09:38:33.661 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:38:39.467 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:38:39.468 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 29
2025-04-07 09:38:39.468 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:38:45.449 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:38:45.450 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 30
2025-04-07 09:38:45.450 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:38:51.238 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:38:51.239 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 31
2025-04-07 09:38:51.239 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:38:56.980 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:38:56.996 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 32
2025-04-07 09:38:56.996 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:39:02.715 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:39:02.716 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 33
2025-04-07 09:39:02.716 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:39:08.523 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:39:08.524 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 34
2025-04-07 09:39:08.524 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:39:14.375 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:39:14.376 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 35
2025-04-07 09:39:14.376 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:39:20.206 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:39:20.206 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 36
2025-04-07 09:39:20.207 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:39:26.064 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:39:26.064 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 37
2025-04-07 09:39:26.064 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:39:31.793 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:39:31.802 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 38
2025-04-07 09:39:31.803 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:39:37.520 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:39:37.521 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 39
2025-04-07 09:39:37.521 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:39:43.267 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:39:43.268 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 40
2025-04-07 09:39:43.268 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:39:48.853 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:39:48.853 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 41
2025-04-07 09:39:48.854 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:39:54.457 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:39:54.457 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 42
2025-04-07 09:39:54.458 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:40:00.051 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:40:00.051 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 43
2025-04-07 09:40:00.052 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:40:05.903 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:40:05.915 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 44
2025-04-07 09:40:05.915 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:40:11.579 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:40:11.580 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 45
2025-04-07 09:40:11.580 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:40:17.519 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:40:17.520 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 46
2025-04-07 09:40:17.520 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:40:23.813 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:40:23.814 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 47
2025-04-07 09:40:23.814 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:40:31.269 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:40:33.272 +05:30 [INF] Application starting up
2025-04-07 09:40:33.537 +05:30 [INF] Main thread ID: 1
2025-04-07 09:40:33.537 +05:30 [INF] ARGS:- C:\BackOffice\ETL_Replacement\PIL\SBINSUN\Input\Source\Temp_Process\SBINSUN_11_v2_20250207_Test1001.csv
2025-04-07 09:40:33.539 +05:30 [INF] Processing files for domain: PIL, invoiceType: SBINSUN
2025-04-07 09:40:38.263 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:40:38.264 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 1
2025-04-07 09:40:38.264 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:40:44.124 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:40:44.125 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 2
2025-04-07 09:40:44.125 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:40:51.011 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:40:51.012 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 3
2025-04-07 09:40:51.012 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:40:56.913 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:40:56.914 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 4
2025-04-07 09:40:56.914 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:41:02.727 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:41:02.727 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 5
2025-04-07 09:41:02.728 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:41:08.922 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:41:08.924 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 6
2025-04-07 09:41:08.934 +05:30 [ERR] Exception: 42703: column "cbcbsttaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:43:40.577 +05:30 [INF] Application starting up
2025-04-07 09:43:40.841 +05:30 [INF] Main thread ID: 1
2025-04-07 09:43:40.841 +05:30 [INF] ARGS:- C:\BackOffice\ETL_Replacement\PIL\SBINSUN\Input\Source\Temp_Process\SBINSUN_11_v2_20250207_Test1001.csv
2025-04-07 09:43:40.843 +05:30 [INF] Processing files for domain: PIL, invoiceType: SBINSUN
2025-04-07 09:43:45.836 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsstaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:43:45.836 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 1
2025-04-07 09:43:45.836 +05:30 [ERR] Exception: 42703: column "cbcbsstaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:43:51.543 +05:30 [WRN] Exception In TempInsertStoreProc: 42703: column "cbcbsstaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:43:51.544 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 2
2025-04-07 09:43:51.544 +05:30 [ERR] Exception: 42703: column "cbcbsstaxcategory" of relation "sbinsun_temp_invoice1" does not exist
2025-04-07 09:45:00.803 +05:30 [INF] Application starting up
2025-04-07 09:45:01.073 +05:30 [INF] Main thread ID: 1
2025-04-07 09:45:01.073 +05:30 [INF] ARGS:- C:\BackOffice\ETL_Replacement\PIL\SBINSUN\Input\Source\Temp_Process\SBINSUN_11_v2_20250207_Test1001.csv
2025-04-07 09:45:01.075 +05:30 [INF] Processing files for domain: PIL, invoiceType: SBINSUN
2025-04-07 09:45:07.880 +05:30 [INF] Process file path :- C:\BackOffice\ETL_Replacement\PIL\SBINSUN\Input\Source\Temp_Process\SBINSUN_11_v2_20250207_Test1001.csv
2025-04-07 09:45:07.880 +05:30 [INF] Process file name :- SBINSUN_11_v2_20250207_Test1001.csv
2025-04-07 09:45:07.880 +05:30 [INF] Total time taken in process: 4.1240665 seconds
2025-04-07 09:45:07.882 +05:30 [INF] Total time taken in moving: 0.0020488 seconds
2025-04-07 10:30:57.707 +05:30 [INF] Application starting up
2025-04-07 10:31:01.055 +05:30 [INF] Main thread ID: 1
2025-04-07 10:31:01.055 +05:30 [INF] ARGS:- C:\BackOffice\ETL_Replacement\PIL\SBINSUN\Input\Source\Temp_Process\SBINSUN_11_v2_20250207_Test1001.csv
2025-04-07 10:31:01.058 +05:30 [INF] Processing files for domain: PIL, invoiceType: SBINSUN
2025-04-07 10:31:06.441 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 1
2025-04-07 10:31:06.441 +05:30 [ERR] Exception: 42703: column di.cbcbuyervatid does not exist
2025-04-07 10:34:46.812 +05:30 [INF] Application starting up
2025-04-07 10:34:47.077 +05:30 [INF] Main thread ID: 1
2025-04-07 10:34:47.077 +05:30 [INF] ARGS:- C:\BackOffice\ETL_Replacement\PIL\SBINSUN\Input\Source\Temp_Process\SBINSUN_11_v2_20250207_Test1001.csv
2025-04-07 10:34:47.079 +05:30 [INF] Processing files for domain: PIL, invoiceType: SBINSUN
2025-04-07 10:34:50.650 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 1
2025-04-07 10:34:50.650 +05:30 [ERR] Exception: 42703: column di.cbcbuyername does not exist
2025-04-07 10:35:41.339 +05:30 [INF] Application starting up
2025-04-07 10:35:41.603 +05:30 [INF] Main thread ID: 1
2025-04-07 10:35:41.603 +05:30 [INF] ARGS:- C:\BackOffice\ETL_Replacement\PIL\SBINSUN\Input\Source\Temp_Process\SBINSUN_11_v2_20250207_Test1001.csv
2025-04-07 10:35:41.605 +05:30 [INF] Processing files for domain: PIL, invoiceType: SBINSUN
2025-04-07 10:35:45.369 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 1
2025-04-07 10:35:45.370 +05:30 [ERR] Exception: 42703: column di.cbcsellersstregistrationnumber does not exist
2025-04-07 10:35:51.955 +05:30 [ERR] Connection failed. Retrying in 5 seconds... Attempt 2
2025-04-07 10:35:51.955 +05:30 [ERR] Exception: 42703: column di.cbcsellersstregistrationnumber does not exist
2025-04-07 10:37:14.462 +05:30 [INF] Application starting up
2025-04-07 10:37:14.728 +05:30 [INF] Main thread ID: 1
2025-04-07 10:37:14.728 +05:30 [INF] ARGS:- C:\BackOffice\ETL_Replacement\PIL\SBINSUN\Input\Source\Temp_Process\SBINSUN_11_v2_20250207_Test1001.csv
2025-04-07 10:37:14.730 +05:30 [INF] Processing files for domain: PIL, invoiceType: SBINSUN
2025-04-07 10:37:18.458 +05:30 [INF] Process file path :- C:\BackOffice\ETL_Replacement\PIL\SBINSUN\Input\Source\Temp_Process\SBINSUN_11_v2_20250207_Test1001.csv
2025-04-07 10:37:18.458 +05:30 [INF] Process file name :- SBINSUN_11_v2_20250207_Test1001.csv
2025-04-07 10:37:18.459 +05:30 [INF] Total time taken in process: 2.7088244 seconds
2025-04-07 10:37:18.461 +05:30 [INF] Total time taken in moving: 0.001745 seconds
